name = "TomoForward"
uuid = "5ddc0d3c-5a45-4284-bfe5-a46ebcced908"
repo = "https://github.com/JuliaTomo/TomoForward.jl"
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
